# Generated by Django 5.0.4 on 2024-04-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodlogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='status_enum_user1',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='status_enum_user2',
        ),
        migrations.AddField(
            model_name='friendship',
            name='sender',
            field=models.IntegerField(choices=[(1, 'User1'), (2, 'User2')], default=1),
        ),
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('ACC', 'Accepted'), ('PEN', 'Pending'), ('DEC', 'Declined')], default='PEN', max_length=3),
        ),
    ]
